name: Python Test, Lint and Build

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Update pip and install pip dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry pylint
    - name: Install poetry
      run: |
        poetry cache clear . --all
        poetry install
    - name: Lint with pylint
      run: |
        pylint $(git ls-files '*.py' -x 'test_*.py')
    - name: Test with pytest
      run: |
        python -m poetry run pytest
  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
    - name: Build whl
      run: |
        python -m poetry build
    - name: Publish to PyPi
      with:
        user: __token__
        password: ${{ secrets.PYPI_POETRY_API }}
      run: |
        python -m poetry publish -u $user -p $password
